### ISSUE TITLE
Query string doesn't escape `+` character

### ISSUE THREAD

**Issue by athanclark** [slamdata/purescript-uri#25]
Express treats `+` as a space character, while this library doesn't percent-encode it. Do you think we could add that feature? I think I saw relevant code in `Data.URI.Common`, under `printFragmentOrQuery` - I think the regex for matching might be misleading.

**Comment by garyb** [comment]
Ughhh. We recently (v4) changed the behaviour of this to behave more correctly... `+` is only supposed to be treated as a space in `application/x-www-form-urlencoded` post data.

I'll trawl the spec some more and see if I can find some examples to see whether the current behaviour is correct or not. I'm not sure what to suggest if this is a bug in express - I imagine it's probably an "intentional bug" in that it is often incorrectly expected to work this way, even though it's not as the spec says.

**Comment by garyb** [comment]
Yeah, I _think_ what we're doing is correct. RF3986 [defines](https://tools.ietf.org/html/rfc3986#appendix-A) the query component of a URL:

```
query         = *( pchar / "/" / "?" )

pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```

So if we added percent encoding for `+`, it would mean that parsing and then printing a URL would potentially change its meaning.

Perhaps we need an alternative (or customisable) pretty printer that will print URLs for browsers in a different way with additional special cases for things like this. The [wikipedia article on query strings](https://en.wikipedia.org/wiki/Query_string) suggests it's not particularly well behaved for browsers in general.

**Comment by athanclark** [comment]
Ah wow I thought x-www-urlencoded was the standard for all percent-encoded query strings. It sounds like this is an express bug, though. I don't see why I can't just make bindings to Node's lower level HTTP gunk, and make a better web server lib intended for purescript.

Thank you for your help and expertise!!

**Comment by garyb** [comment]
I'm not really sure what the expected behaviour should be here really - I think it's just ambiguous, since it seems that it's undefined in general as to how `+` should be treated, and it's left up to the consumer to determine the appropriate behaviour.

Assuming you don't want to rewrite express :wink: (or switch to using something like [Hyper](https://hyper.wickstrom.tech/)) I'd suggest writing a custom renderer for your app perhaps?

If it's a persistent problem people have then we probably should add some stuff to the library to support it.

**Comment by athanclark** [comment]
I'm plumbing a base64 string in a query parameter - I was considering just swapping `+` with another character, but I think I'll just try Hyper. I think it would be useful to have express compatibility in this lib, but... I would rather see people adopt a different tech like Hyper.

Thank you again for your help!!
