### ISSUE TITLE
`printFragmentOrQuery` and printing Query part 

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-uri#27]
It seems that this function (`printFragmentOrQuery`) breaks printing of `Query` type. 
I.e. if I have `{foo: "bar?baz"}` this will be printed as `?foo=bar?baz` but should be printed as `?foo=bar%3Fbaz`

**Comment by garyb** [comment]
Not according to [the spec](https://tools.ietf.org/html/rfc3986#appendix-A), it says the query part can contain:

```
query         = *( pchar / "/" / "?" )
```

(pchar etc. omitted since it's irrelevant here, but you can see `?` is specifically allowed as an unencoded character).

A similar issue was raised in #25, it seems that a lot of things are not well behaved in regards to the spec, so we might need to pre-encode/write alternative renderers for some of this stuff...

**Comment by cryogenian** [comment]
You mean on clientside? Ooh...

**Comment by cryogenian** [comment]
Well that may be, but then the parser is broken :( I.e. 
```
sql2:///?q=CREATE%20FUNCTION%20foo%28%3Ax%29%0A%20%20BEGIN%0A%20%20%20%20x%0A%20%20END%3B%0A%28select%20foo%2812%29%29
```
emits 
```purescript
AbsoluteURI (Just "sql2") (HirarchicalPart (Just (Authority Nothing)) (Just (Left Root))) (Just (Query (L.Cons (Tuple "q" $ Just "CREATE ...") (Tuple "select foo(..." Nothing))
```

**Comment by garyb** [comment]
Ah I see! That might well be the case, lemme see...
